#!groovy

library("shared-library@master") _

properties([
    parameters([
        prop.choiceOfLibraryBranch()
    ])
])

library("shared-library@${pipelineSharedLibrary}") _
node {
    ls()
}