#!groovy

library("shared-library@feature-2") _

properties([
    parameters([
        prop.choiceOfLibraryBranch()
    ])
])

library("shared-library@${pipelineSharedLibrary}") _
node {
    ex()
    ex.someFunction()
}